image: alpine:latest
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

stages:
  - test
  - package

build_and_test:
  stage: test
  image: node:18
  services:
    - name: selenium/standalone-firefox
      alias: firefox
    - name: selenium/standalone-chrome
      alias: chrome
  variables:
    WEBDRIVER_DISABLE_SHM: 'true'
    WEBDRIVER_HOST_CHROME: chrome:4444
    WEBDRIVER_HOST_FIREFOX: firefox:4444
    TESTRUNNER_HOST: '0.0.0.0'
  script:
    - npm install-test
  artifacts:
    name: web
    expire_in: 20 minutes
    paths:
      - web

pages:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  dependencies:
    - build_and_test
  script:
    - mv web public
  artifacts:
    paths:
      - public
