image: alpine:latest
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

stages:
  - test
  - package

.build_and_test: &build_and_test
  stage: test
  services:
    - name: selenium/standalone-firefox
      alias: firefox
    - name: selenium/standalone-chrome
      alias: chrome
  variables:
    WEBDRIVER_DISABLE_SHM: 'true'
    WEBDRIVER_HOST_CHROME: chrome:4444
    WEBDRIVER_HOST_FIREFOX: firefox:4444
    TESTRUNNER_HOST: '0.0.0.0'
  script:
    - npm install-test

node:20:
  <<: *build_and_test
  image: node:20

node:22:
  <<: *build_and_test
  image: node:22

node:24:
  <<: *build_and_test
  image: node:24
  artifacts:
    name: web
    expire_in: 20 minutes
    paths:
      - web

pages:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  dependencies:
    - node:20
    - node:22
    - node:24
  script:
    - mv web public
  artifacts:
    paths:
      - public
